### ISSUE TITLE
hide the logger better

### ISSUE THREAD

**Issue by thisusercannotcode** [2tacey/exeter-selfbot-source-code#10]
took 2 seconds to find the logger 😂

**Comment by cyxl** [comment]
it took 0.531243123 seconds to find it for me.

**Comment by wn7** [comment]
so it is a token logger ? lol
Where can the real source be found then

**Comment by cyxl** [comment]
@wn7  if you look at the pull request That’s a clean version of it and also the web doesn’t work anymore so they’re technically is no logger

**Comment by wn7** [comment]
> @wn7 if you look at the pull request That’s a clean version of it and also the web doesn’t work anymore so they’re technically is no logger

yeah i got the source, im in a deep shit that idk how to convert the py file to exe, i mean, i know but when i coverted it it doesnt work. if you can help me, dm me on dc wNtRR#1068

**Comment by cyxl** [comment]
> > @wn7 if you look at the pull request That’s a clean version of it and also the web doesn’t work anymore so they’re technically is no logger
> 
> yeah i got the source, im in a deep shit that idk how to convert the py file to exe, i mean, i know but when i coverted it it doesnt work. if you can help me, dm me on dc wNtRR#1068

Right now I am banned from discord for 7 days but if you wanna use telegram thats fine also research pyinstaller thats what I use or just run it using python

**Comment by wn7** [comment]
> > > @wn7 if you look at the pull request That’s a clean version of it and also the web doesn’t work anymore so they’re technically is no logger
> > 
> > 
> > yeah i got the source, im in a deep shit that idk how to convert the py file to exe, i mean, i know but when i coverted it it doesnt work. if you can help me, dm me on dc wNtRR#1068
> 
> Right now I am banned from discord for 7 days but if you wanna use telegram thats fine also research pyinstaller thats what I use or just run it using python

instagram ? (@akawntrr)

**Comment by wn7** [comment]
> > > @wn7 if you look at the pull request That’s a clean version of it and also the web doesn’t work anymore so they’re technically is no logger
> > 
> > 
> > yeah i got the source, im in a deep shit that idk how to convert the py file to exe, i mean, i know but when i coverted it it doesnt work. if you can help me, dm me on dc wNtRR#1068
> 
> Right now I am banned from discord for 7 days but if you wanna use telegram thats fine also research pyinstaller thats what I use or just run it using python

yo bro i actually need help now, im trying to convert the fkn .py file to .exe but its not working, keeps closing instantly. Im trying to convert it for 4 hours now, can you hit me up on instagram (@akawntrr) or on smth else ?

**Comment by cyxl** [comment]
> > > > @wn7 if you look at the pull request That’s a clean version of it and also the web doesn’t work anymore so they’re technically is no logger
> > > 
> > > 
> > > yeah i got the source, im in a deep shit that idk how to convert the py file to exe, i mean, i know but when i coverted it it doesnt work. if you can help me, dm me on dc wNtRR#1068
> > 
> > 
> > Right now I am banned from discord for 7 days but if you wanna use telegram thats fine also research pyinstaller thats what I use or just run it using python
> 
> yo bro i actually need help now, im trying to convert the fkn .py file to .exe but its not working, keeps closing instantly. Im trying to convert it for 4 hours now, can you hit me up on instagram (@akawntrr) or on smth else ?

yea man ill hit you up soon in school rn.
