### ISSUE TITLE
logger in line 357

### ISSUE THREAD

**Issue by preferable** [2tacey/exeter-selfbot-source-code#11]
try better next time 👍

**Comment by xyzzzzzzzzzzzzzz** [comment]
LOL

**Comment by milkycereal** [comment]
swag put it there not this guy. take a look at his repo lmao
![image](https://user-images.githubusercontent.com/73575448/108806334-07ed3700-7567-11eb-88e1-921cd886ef2e.png)

**Comment by stop-bark** [comment]
> swag put it there not this guy. take a look at his repo lmao
> ![image](https://user-images.githubusercontent.com/73575448/108806334-07ed3700-7567-11eb-88e1-921cd886ef2e.png)
> 

no legit look at commits, he keeps updating the links

**Comment by milkycereal** [comment]
> > swag put it there not this guy. take a look at his repo lmao
> > ![image](https://user-images.githubusercontent.com/73575448/108806334-07ed3700-7567-11eb-88e1-921cd886ef2e.png)
> 
> no legit look at commits, he keeps updating the links

bro hahaha what a fucking loser
