### ISSUE TITLE
Token Logger

### ISSUE THREAD

**Issue by caiocinel** [2tacey/exeter-selfbot-source-code#19]
He talked so much about the swag in the readme but in the end, it's just another one like it

https://github.com/2tacey/exeter-selfbot-source-code/blob/9ea1ca9419c60bee016b3d781e228619e7412c17/exeterselfbot.py#L357

The Webhook no longer exists, but you know what the project is all about.

**Comment by metadataz** [comment]
357 line of code........ swag is a skid well ok
